addons:
  ssh_known_hosts: russellhay.com
language: go
go:
- tip
install:
#- go get -u -v github.com/kardianos/govendor
- go get -u -v github.com/spf13/hugo
#- cd $GOPATH/src/github.com/spf13/hugo && govendor sync && go install
script:
#- cd $GOPATH/src/github.com/stainlessio/thechaseshort
- hugo
notifications:
  email:
    on_failure: always

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet $TRAVIS_BUILD_DIR/public/ deploy@russellhay.com:/home/www/thechase/
  on:
    branch: master

before_install:
- openssl aes-256-cbc -K $encrypted_e3e7a38390b3_key -iv $encrypted_e3e7a38390b3_iv
  -in deploy_rsa.enc -out deploy_rsa -d

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy.rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy.rsa